name: Apply updates from issue comments

on:
  issue_comment:
    types: [created]

permissions:
  contents: write

jobs:
  apply:
    if: contains(github.event.comment.body, '/apply-update')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Apply payload from comment
        env:
          COMMENT_BODY: ${{ github.event.comment.body }}
        run: |
          python - <<'PY'
          import os, sys, re, json, base64, pathlib
          body = os.environ['COMMENT_BODY']
          m = re.search(r"```update\s*(.*?)\s*```", body, re.S)
          if not m:
              print("::error::No ```update code block found")
              sys.exit(1)
          payload = json.loads(m.group(1))
          files = payload.get("files", [])
          if not files:
              print("::error::No files in payload")
              sys.exit(1)
          for f in files:
              p = pathlib.Path(f["path"])
              p.parent.mkdir(parents=True, exist_ok=True)
              p.write_bytes(base64.b64decode(f["content_b64"]))
          open("commit_msg.txt","w").write(payload.get("message","Update via /apply-update"))
          open("branch.txt","w").write(payload.get("branch","main"))
          PY

      - name: Commit and push
        run: |
          BRANCH=$(cat branch.txt)
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout -B "$BRANCH"
          git add -A
          git commit -m "$(cat commit_msg.txt)" || echo "No changes to commit"
          git push origin "$BRANCH"
